apiVersion: v2
appVersion: v3.1.8
description: Agave blockchain node Helm chart
keywords:
- agave
- solana
- anza-xyz
- crypto
- web3
- cryptocurrency
- blockchain
maintainers:
- email: vlad.derigin@dysnix.com
  name: VladStarr
name: agave
sources:
- https://github.com/dysnix/charts
- https://github.com/dysnix/docker-agave
- https://github.com/anza-xyz/agave
type: application
version: 0.4.0
