{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "op-node.fullname" . }}
  labels:
    {{- include "op-node.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      service-type: metrics
      {{- include "op-node.labels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /metrics
      {{- with (omit .Values.serviceMonitor "enabled") }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
{{- end }}
