apiVersion: v2
name: op-node
description: Optimism op-node consensus-layer client Helm chart

version: 0.1.0
appVersion: v1.4.2

keywords:
  - rollup
  - consensus
  - optimism
  - op-node
  - cryptocurrency
  - blockchain

sources:
  - https://github.com/dysnix/charts

maintainers:
  - name: VladStarr
    email: vladstarrr@icloud.com
