remote: origin
chart-dirs:
  - dysnix/
chart-repos:
  - stable=https://charts.helm.sh/stable
  - bitnami=https://charts.bitnami.com/bitnami
  - grafana=https://grafana.github.io/helm-charts
excluded-charts:
  - ai-base
debug: true
check-version-increment: true
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
