remote: origin
target-branch: main
chart-dirs:
  - dysnix/
chart-repos:
  - dysnix=https://dysnix.github.io/charts
  - stable=https://charts.helm.sh/stable
  - bitnami=https://charts.bitnami.com/bitnami
  - grafana=https://grafana.github.io/helm-charts
excluded-charts: []
debug: true
check-version-increment: true
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
