apiVersion: v2
name: eth-cache-proxy
description: A Helm chart for Kubernetes
type: application
version: 0.1.11
appVersion: "0.0.2"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.10.x
  - name: base
    version: 0.2.x
    repository: https://dysnix.github.io/charts
    tags:
      - dysnix-base
  - name: redis
    version: 15.6.x
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
    tags:
      - bitnami-redis
sources:
  - https://github.com/dysnix/charts
maintainers:
  - email: services@dysnix.com
    name: Dysnix
