apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxysql_cluster.satellite.service.name | default (printf "%s" ( include "proxysql.fullname" . )) | quote }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq .Values.service.type "LoadBalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{ with .Values.service.loadBalancerSourceRanges }}
{{ toYaml . | indent 4 }}
{{- end }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      {{- if .Values.service.proxyNodePort }}
      nodePort: {{ .Values.service.proxyNodePort }}
      {{- end }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      {{- if .Values.service.adminNodePort }}
      nodePort: {{ .Values.service.adminNodePort }}
      {{- end }}
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      {{- if .Values.service.webNodePort }}
      nodePort: {{ .Values.service.webNodePort }}
      {{- end }}
  selector:
    app: {{ include "proxysql.name" . }}
    release: {{ .Release.Name }}
---
{{ if and .Values.proxysql_cluster.enabled .Values.proxysql_cluster.core.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.proxysql_cluster.core.service.name | default (printf "%s-core" (include "proxysql.fullname" .)) | quote }}
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  annotations:
    {{- if .Values.commonAnnotations }}
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
    {{- end }}
    {{- with .Values.service.annotations }}
    {{- tpl (toYaml .) $ | nindent 4 }}
    {{- end }}
spec:
  ports:
    - name: proxy
      port: {{ .Values.service.proxyPort }}
      targetPort: proxy
      {{- if .Values.service.proxyNodePort }}
      nodePort: {{ .Values.service.proxyNodePort }}
      {{- end }}
    - name: admin
      port: {{ .Values.service.adminPort }}
      targetPort: admin
      {{- if .Values.service.adminNodePort }}
      nodePort: {{ .Values.service.adminNodePort }}
      {{- end }}
    - name: web
      port: {{ .Values.service.webPort }}
      targetPort: web
      {{- if .Values.service.webNodePort }}
      nodePort: {{ .Values.service.webNodePort }}
      {{- end }}
  clusterIP: None
  selector:
    app: {{ include "proxysql.name" . }}-core
    release: {{ .Release.Name }}
{{ end }}
