{{- if and .Values.proxysql_cluster.core.enabled .Values.proxysql_cluster.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proxysql.fullname" . }}-core
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.proxysql_cluster.core.replicas }}
  selector:
    matchLabels:
      app: {{ include "proxysql.name" . }}-core
      release: {{ .Release.Name }}
  serviceName: {{ include "proxysql.fullname" . }}-core
  template:
    metadata:
      annotations:
        # Automatically Roll Deployments
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
      {{- with (default .Values.podAnnotations .Values.proxysql_cluster.core.statefullset.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app: {{ include "proxysql.name" . }}-core
        release: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      containers:
        - name: {{ .Chart.Name }}
          command: ["proxysql", "-c", "/etc/proxysql/proxysql.cnf", "-f"]
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "proxysql.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: 6033
              protocol: TCP
            - name: admin
              containerPort: 6032
              protocol: TCP
            - name: web
              containerPort: 6080
              protocol: TCP
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            exec:
              command: ["bash", "-c", "true <>/dev/tcp/127.0.0.1/6033"]
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          resources:
            {{- toYaml (default .Values.resources .Values.proxysql_cluster.core.statefullset.resources) | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data/proxysql
            - name: conf
              mountPath: /etc/proxysql/proxysql.cnf
              subPath: proxysql.cnf
            - name: secrets
              mountPath: /etc/proxysql/admin_credentials.cnf
              subPath: admin_credentials.cnf
          {{- if .Values.ssl.fromSecret }}
            - name: ssl
              mountPath: /etc/proxysql/ssl
          {{- end }}
        {{- if .Values.debug.sidecar.enabled }}
        - name: debug
          image: {{.Values.debug.sidecar.image}}
          command:
            {{- toYaml .Values.debug.sidecar.command | nindent 14 }}
          securityContext:
            runAsGroup: 1001
            runAsUser: 1001
        {{- end }}
      {{- with (default .Values.nodeSelector .Values.proxysql_cluster.core.statefullset.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with (default .Values.affinity .Values.proxysql_cluster.core.statefullset.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with (default .Values.tolerations .Values.proxysql_cluster.core.statefullset.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | int }}
      volumes:
        - name: data
          emptyDir: {}
        - name: secrets
          secret:
            secretName: {{ include "proxysql.fullname" . }}
            defaultMode: 0640
        - name: conf
          configMap:
            name: {{ include "proxysql.fullname" . }}
        {{- with .Values.ssl.fromSecret }}
        - name: ssl
          secret:
            secretName: {{ . }}
            defaultMode: 0640
        {{- end }}
{{- end }}
