{{- if and .Values.proxysql_cluster.core.enabled .Values.proxysql_cluster.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "proxysql.fullname" . }}-core
  labels:
    {{- include "proxysql.labels" . | nindent 4 }}
    {{- if .Values.commonLabels }}
    {{- toYaml .Values.commonLabels | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations:
    {{- toYaml .Values.commonAnnotations | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.proxysql_cluster.core.replicas }}
  selector:
    matchLabels:
      {{- include "proxysql.core.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "proxysql.fullname" . }}-core
  template:
    metadata:
      annotations:
        # Automatically Roll Deployments
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/config.scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        {{- with (mergeOverwrite .Values.podAnnotations .Values.proxysql_cluster.core.statefullset.podAnnotations) }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "proxysql.core.selectorLabels" . | nindent 8 }}
        {{- if .Values.commonLabels }}
        {{- toYaml .Values.commonLabels | nindent 8 }}
        {{- end }}
        {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ template "proxysql.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      dnsPolicy: ClusterFirst
      shareProcessNamespace: true
      containers:
        - name: proxysql
          command:
            - "proxysql"
            - "-c"
            - "/etc/proxysql/proxysql.cnf"
            - "-f"
            - "--idle-threads"
            {{- if .Values.proxysql_cluster.core.exit_on_error }}
            - "--exit-on-error"
            {{- end }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: {{ template "proxysql.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          lifecycle:
            preStop:
              exec:
                command: ["/bin/sh", "-c", "/usr/local/bin/wait_queries_to_finish.sh > /proc/1/fd/1"]
          ports:
            - name: proxy
              containerPort: {{ .Values.service.proxyPort }}
              protocol: TCP
            - name: admin
              containerPort: {{ .Values.service.adminPort }}
              protocol: TCP
            - name: web
              containerPort: {{ .Values.service.webPort }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe: {{ toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml (default .Values.resources .Values.proxysql_cluster.core.statefullset.resources) | nindent 12 }}
          volumeMounts:
            {{- with .Values.volumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
            - name: data
              mountPath: /data/proxysql
            - name: conf
              mountPath: /etc/proxysql/proxysql.cnf
              subPath: proxysql.cnf
            - name: secrets
              mountPath: /etc/proxysql/admin_credentials.cnf
              subPath: admin_credentials.cnf
            - name: scripts
              mountPath: /usr/local/bin/wait_queries_to_finish.sh
              subPath: wait_queries_to_finish.sh
          {{- if .Values.ssl.fromSecret }}
            - name: ssl
              mountPath: /etc/proxysql/ssl
          {{- else }}
            {{- if .Values.ssl.ca }}
            - name: secrets
              mountPath: {{ include "proxysql.sslDir" . }}/{{ .Values.ssl.ca_file }}
              subPath: ca.pem
            {{- end }}
            {{- if .Values.ssl.cert }}
            - name: secrets
              mountPath: {{ include "proxysql.sslDir" . }}/{{ .Values.ssl.cert_file }}
              subPath: cert.pem
            {{- end }}
            {{- if .Values.ssl.key }}
            - name: secrets
              mountPath: {{ include "proxysql.sslDir" . }}/{{ .Values.ssl.key_file }}
              subPath: key.pem
            {{- end }}
          {{- end }}
        {{- if .Values.debug.sidecar.enabled }}
        - name: debug
          image: {{ .Values.debug.sidecar.image }}
          command:
            {{- toYaml .Values.debug.sidecar.command | nindent 14 }}
          {{- with .Values.debug.sidecar.securityContext }}
          securityContext:
            {{- toYaml .| nindent 12 }}
          {{- end }}
        {{- end }}
        {{- if and .Values.proxysql_cluster.enabled .Values.proxysql_cluster.healthcheck.sidecar.enabled }}
        - name: healthcheck
          image: {{ .Values.proxysql_cluster.healthcheck.sidecar.image }}
          command:
            {{- toYaml .Values.proxysql_cluster.healthcheck.sidecar.command | nindent 14 }}
          envFrom:
            - configMapRef:
                name: '{{ include "proxysql.fullname" . }}-healthcheck'
            - secretRef:
                name: '{{ include "proxysql.fullname" . }}-healthcheck'
          volumeMounts:
            - name: scripts
              mountPath: /usr/local/bin/proxysql_cluster_healthcheck.sh
              subPath: proxysql_cluster_healthcheck.sh
          {{- with .Values.proxysql_cluster.healthcheck.sidecar.securityContext }}
          securityContext:
            {{- toYaml .| nindent 12 }}
          {{- end }}
        {{- end }}
      {{- with (default .Values.nodeSelector .Values.proxysql_cluster.core.statefullset.nodeSelector) }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with (default .Values.affinity .Values.proxysql_cluster.core.statefullset.affinity) }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with (default .Values.tolerations .Values.proxysql_cluster.core.statefullset.tolerations) }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds | int }}
      volumes:
        {{- with .Values.volumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        - name: data
          emptyDir: {}
        - name: secrets
          secret:
            secretName: {{ include "proxysql.fullname" . }}
            defaultMode: 0640
        - name: conf
          configMap:
            name: {{ include "proxysql.fullname" . }}
        {{- with .Values.ssl.fromSecret }}
        - name: ssl
          secret:
            secretName: {{ . }}
            defaultMode: 0640
        {{- end }}
        - name: scripts
          configMap:
            name: {{ include "proxysql.fullname" . }}-scripts
            items:
              - key: wait_queries_to_finish.sh
                path: wait_queries_to_finish.sh
                mode: 0777
              - key: proxysql_cluster_healthcheck.sh
                path: proxysql_cluster_healthcheck.sh
                mode: 0777
{{- end }}
