{{- if or .Values.initFromS3.enabled .Values.syncToS3.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "op-geth.fullname" . }}-s3-config
data:
  DATA_DIR: {{ tpl .Values.s3config.local.datadir . | quote }}
  INITIALIZED_FILE: {{ tpl .Values.s3config.local.initializedFile . | quote }}
  SYNC_TO_S3: "False"
  S3_BASE_URL: {{ tpl .Values.s3config.remote.baseUrl . }}
  FORCE_INIT: {{ ternary "True" "False" .Values.initFromS3.force | quote }}
{{- end }}
