{{- if .Values.syncToS3.cronjob.enabled -}}
{{- $fullName := print (include "op-geth.fullname" .) "-s3-cronjob" }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $fullName }}
  labels: {{ include "op-geth.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ $fullName }}
  labels: {{ include "op-geth.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
      - delete
  - apiGroups: [""]
    resources:
      - configmaps
    resourceNames:
      - {{ include "op-geth.fullname" . }}-s3-config
    verbs:
      - get
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ $fullName }}
  labels: {{ include "op-geth.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ $fullName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ $fullName }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
