apiVersion: v1
kind: Secret
metadata:
  name: {{ template "op-geth.fullname" . }}
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
data:
  jwt.hex: {{ .Values.config.jwt | b64enc | quote }}