apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ template "op-geth.fullname" . }}
  labels:
    {{- include "op-geth.labels" . | nindent 4 }}
spec:
  serviceName: {{ template "op-geth.name" . }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "op-geth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      labels:
        {{- include "op-geth.selectorLabels" . | nindent 8 }}
        {{- with .Values.podStatusLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "op-geth.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      {{- if .Values.init.download.enabled }}
      - name: init-download
        image: "{{ .Values.init.download.image.repository }}:{{ .Values.init.download.image.tag }}"
        imagePullPolicy: {{ .Values.init.download.image.pullPolicy | quote }}
        command: ["sh", "/scripts/init-download.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: data
          mountPath: /root/.ethereum
      {{- end }}
      {{- if .Values.init.genesis.enabled }}
      - name: init-genesis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command: ["sh", "/scripts/init-genesis.sh"]
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: data
          mountPath: /root/.ethereum
      {{- end }}
      {{- with .Values.extraInitContainers }}
        {{- tpl (toYaml . | nindent 6) $ }}
      {{- end }}
      containers:
      - name: op-geth
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.command }}
        command:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        args:
        {{- with .Values.config.network }}
        - --op-network={{ . }}
        {{- end }}
        - --syncmode={{ .Values.config.syncmode }}
        - --maxpeers=0
        - --nodiscover
        - --authrpc.addr=0.0.0.0
        - --authrpc.jwtsecret=/secrets/jwt.hex
        - --authrpc.vhosts={{ join "," .Values.config.authrpc.vhosts }}
        - --authrpc.port={{ .Values.config.authrpc.port }}
        - --http
        - --http.addr=0.0.0.0
        - --http.port={{ .Values.config.http.port }}
        - --http.api={{ join "," .Values.config.http.api }}
        - --http.vhosts={{ join "," .Values.config.http.vhosts }}
        - --http.corsdomain={{ join "," .Values.config.http.corsdomain }}
        {{- if .Values.config.cache }}
        - --cache={{ .Values.config.cache }}
        {{- end }}
        - --gcmode={{ .Values.config.gcmode }}
        - --snapshot={{ .Values.config.snapshot }}
        {{- with .Values.config.rollup }}
        - --rollup.sequencerhttp={{ .sequencerhttp }}
        - --rollup.disabletxpoolgossip={{ .disabletxpoolgossip }}
        {{- with .halt }}
        - --rollup.halt={{ . }}
        {{- end }}
        {{- end }}
        - --verbosity={{ .Values.config.verbosity }}
        {{- if .Values.config.ws.enabled }}
        - --ws
        - --ws.addr=0.0.0.0
        - --ws.api={{ join "," .Values.config.ws.api }}
        - --ws.origins={{ join "," .Values.config.ws.origins }}
        - --ws.port={{ .Values.config.ws.port }}
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        - --metrics.addr=0.0.0.0
        - --metrics.port=6060
        - --metrics
        {{- if .Values.config.metrics.expensive }}
        - --metrics.expensive
        {{- end }}
        {{- end }}
        {{- with .Values.config.vmodule }}
        - --vmodule={{ join "," . }}
        {{- end }}
        {{- with .Values.extraArgs }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.config.http.port }}
        - name: authrpc
          containerPort: {{ .Values.config.authrpc.port }}
        {{- if .Values.config.ws.enabled }}
        - name: ws
          containerPort: {{ .Values.config.ws.port }}
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        - name: metrics
          containerPort: 6060
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- include "op-geth.healthcheck" (list $ .Values.livenessProbe) | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- include "op-geth.healthcheck" (list $ .Values.readinessProbe) | nindent 10 }}
        {{- end }}
        volumeMounts:
        - name: data
          mountPath: /root/.ethereum
        - name: secrets
          mountPath: /secrets
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
      {{- with .Values.sidecarContainers }}
        {{- tpl (toYaml . | nindent 6) $ }}
      {{- end }}
      volumes:
      - name: secrets
        secret:
          secretName: {{ template "op-geth.fullname" . }}
      - name: scripts
        configMap:
          name: {{ template "op-geth.fullname" . }}-scripts
      {{- if eq .Values.persistence.type "hostPath" }}
      - name: data
        hostPath:
          path: {{ .Values.persistence.hostPath.path }}
          type: {{ .Values.persistence.hostPath.type }}
      {{- end }}
  {{- if eq .Values.persistence.type "pvc" }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "op-geth.selectorLabels" . | nindent 8 }}
      {{- with .Values.persistence.pvc.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
      - {{ .Values.persistence.pvc.accessMode }}
      {{- if .Values.persistence.pvc.storageClass }}
      {{- if eq .Values.persistence.pvc.storageClass "-" }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.persistence.pvc.storageClass | quote }}
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.pvc.size | quote }}
  {{- end }}