myAppConfig:
  mySecret: Hello World!
  multiline: |
    first
    second
  pkey: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----

configMap:
  annotations: {}
  data:
    foo: bar
    hello: world
    multiline: |
      A multi-line value
      This is the second line
    multiline_from_template: |
      {{- .Values.myAppConfig.multiline | trim | nindent 2 }}

secret:
  data:
    MYSECRET: "{{ .Values.myAppConfig.mySecret | b64enc }}"
    SAMESECRET: |
      {{ .Values.myAppConfig.mySecret | b64enc }}

  stringData:
    SECRET_STRING: abc
    SECRET_MULTILINE: |
      -----BEGIN RSA PRIVATE KEY-----
      -----END RSA PRIVATE KEY-----
    SECRET_FROM_TEMPLATE: |
      {{ "Templates are rendered, yay!" }}
    SECRET_FROM_ANOTHER_TPLVALUE: |
      {{- .Values.myAppConfig.pkey | trim | nindent 2 }}
