apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "heimdall.fullname" . }}-scripts
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
data:
  init-genesis.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_init-genesis.tpl") . | nindent 4 }}
  download-snapshot.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_download-snapshot.tpl") . | nindent 4 }}
