apiVersion: v1
appVersion: "2.4.4"
description: ProxySQL Helm chart for Kubernetes
name: proxysql
version: 0.4.1
home: https://www.proxysql.com/
sources:
  - https://github.com/dysnix/charts
  - https://github.com/sysown/proxysql
maintainers:
  - email: services@dysnix.com
    name: Dysnix
