apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "reth.fullname" . }}-scripts
  labels:
    {{- include "reth.labels" . | nindent 4 }}
data:
  readiness.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_readiness.tpl") . | nindent 4 }}
  liveness.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_liveness.tpl") . | nindent 4 }}
  startup.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_startup.tpl") . | nindent 4 }}
