{{- if or .Values.services.metrics.enabled .Values.metricsExtra.enabled }}
{{- with .Values.services.metrics }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" $ }}-metrics
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: metrics
    {{- include "reth.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    {{- if .enabled }}
    - name: metrics
      port: {{ .port }}
      targetPort: metrics
    {{- end }}
    {{- if $.Values.metricsExtra.enabled }}
    - name: {{ $.Values.metricsExtra.portName }}
      port: {{ $.Values.metricsExtra.port }}
      targetPort: {{ $.Values.metricsExtra.portName }}
    {{- end }}
  selector:
    {{- include "reth.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
