{{- with .Values.services.p2pDiscovery }}
{{- if and .enabled (not $.Values.config.p2p.useHostPort) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reth.fullname" $ }}-p2p-discovery
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: p2p-discovery
    {{- include "reth.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: p2p-udp
      port: {{ .port }}
      targetPort: p2p-udp
      protocol: UDP
      {{- with .nodePort }}
      nodePort: {{ . }}
      {{- end }}
    {{- if $.Values.config.p2p.discv5.enabled }}
    - name: discv5-udp
      port: {{ $.Values.config.p2p.discv5.port }}
      targetPort: discv5-udp
      protocol: UDP
    {{- end }}
  selector:
    {{- include "reth.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
