apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "reth.fullname" . }}
  labels:
    {{- include "reth.labels" . | nindent 4 }}
spec:
  serviceName: {{ template "reth.name" . }}
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "reth.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/scripts: {{ include (print $.Template.BasePath "/configmap-scripts.yaml") . | sha256sum }}
        {{- if or .Values.syncToS3.enabled .Values.initFromS3.enabled }}
        checksum/s3-secret: {{ include (print $.Template.BasePath "/s3-secret.yaml") . | sha256sum }}
        checksum/s3-configmap: {{ include (print $.Template.BasePath "/s3-configmap.yaml") . | sha256sum }}
        {{- end }}
      labels:
        {{- include "reth.selectorLabels" . | nindent 8 }}
        {{- with .Values.podStatusLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      enableServiceLinks: {{ .Values.enableServiceLinks }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      {{- if .Values.shareProcessNamespace }}
      shareProcessNamespace: {{ .Values.shareProcessNamespace }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "reth.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 10 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
      - name: init-config
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "cp /config-ro/reth.toml /config/reth.toml"]
        volumeMounts:
        - name: config-ro
          mountPath: /config-ro
        - name: config
          mountPath: /config
      {{- if .Values.config.p2p.nodeKey }}
      - name: set-node-key
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        command: ["sh", "-c", "echo -n {{ .Values.config.p2p.nodeKey }} > {{ .Values.config.datadir }}/discovery-secret"]
        volumeMounts:
        - name: data
          mountPath: {{ .Values.persistence.mountPath | default .Values.config.datadir }}
      {{- end }}
      {{- if .Values.init.chownData.enabled }}
      - name: chown-data
        image: "{{ .Values.init.chownData.image.repository }}:{{ .Values.init.chownData.image.tag }}"
        imagePullPolicy: {{ .Values.init.chownData.image.pullPolicy | quote }}
        securityContext:
          runAsNonRoot: false
          runAsUser: 0
        command: ["chown", "-R", "{{ .Values.securityContext.runAsUser }}:{{ .Values.securityContext.runAsGroup }}", "/data"]
        volumeMounts:
        - name: data
          mountPath: /data
      {{- end }}
      {{- if .Values.init.download.enabled }}
      - name: reth-download
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
        - sh
        - /scripts/reth-download.sh
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: data
          mountPath: {{ .Values.persistence.mountPath | default .Values.config.datadir }}
      {{- end }}
      {{- if .Values.initFromS3.enabled }}
      {{- with .Values.s3config }}
      - name: init-from-s3
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy | quote }}
        {{- with $.Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
        - sh
        - /scripts/init-from-s3.sh
        envFrom:
        - configMapRef:
            name: {{ include "reth.fullname" $ }}-s3-config
        - secretRef:
            name: {{ include "reth.fullname" $ }}-s3-secret
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: data
          mountPath: {{ $.Values.persistence.mountPath | default $.Values.config.datadir }}
      {{- end }}
      {{- end }}
      {{- if .Values.syncToS3.enabled }}
      {{- with .Values.s3config }}
      - name: sync-to-s3
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy | quote }}
        {{- with $.Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
        - /bin/sh
        - /scripts/sync-to-s3.sh
        envFrom:
        - configMapRef:
            name: {{ include "reth.fullname" $ }}-s3-config
        - secretRef:
            name: {{ include "reth.fullname" $ }}-s3-secret
        volumeMounts:
        - name: scripts
          mountPath: /scripts
        - name: data
          mountPath: {{ $.Values.persistence.mountPath | default $.Values.config.datadir }}
      {{- end }}
      {{- with .Values.syncToS3.cronjob }}
      {{- if .enabled }}
      - name: disable-sync-to-s3
        image: "{{ .image.repository }}:{{ .image.tag }}"
        imagePullPolicy: {{ .image.pullPolicy | quote }}
        {{- with $.Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        command:
        - /bin/sh
        - /scripts/s3-cron.sh
        - disable_sync
        - 5s
        volumeMounts:
        - name: scripts
          mountPath: /scripts
      {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.extraInitContainers }}
        {{- tpl (toYaml . | nindent 6) $ }}
      {{- end }}
      containers:
      {{- with .Values.sidecarContainers }}
        {{- tpl (toYaml . | nindent 6) $ }}
      {{- end }}
      - name: reth
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
        {{- with .Values.securityContext }}
        securityContext:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        {{- with .Values.command }}
        command:
          {{- tpl (toYaml .) $ | nindent 10 }}
        {{- end }}
        {{- if .Values.argsOverride }}
        args:
          {{- tpl (toYaml .Values.argsOverride) $ | nindent 10 }}
        {{- else }}
        args:
        - node
        - --config=/config/reth.toml
        - --datadir={{ .Values.config.datadir }}
        - --chain={{ .Values.config.chain }}
        {{- with .Values.config.syncMode }}
        - --{{ . }}
        {{- end }}
        {{- if .Values.config.http.enabled }}
        - --http
        - --http.addr={{ .Values.config.http.addr }}
        - --http.port={{ .Values.config.http.port }}
        - --http.api={{ join "," .Values.config.http.api }}
        - --http.corsdomain={{ join "," .Values.config.http.corsdomain }}
        {{- end }}
        - --authrpc.addr={{ .Values.config.authrpc.addr }}
        - --authrpc.port={{ .Values.config.authrpc.port }}
        - --authrpc.jwtsecret={{ .Values.config.authrpc.jwtsecret }}
        {{- if .Values.config.ws.enabled }}
        - --ws
        - --ws.addr={{ .Values.config.ws.addr }}
        - --ws.port={{ .Values.config.ws.port }}
        - --ws.origins={{ join "," .Values.config.ws.origins }}
        - --ws.api={{ join "," .Values.config.ws.api }}
        {{- end }}
        - --port={{ .Values.config.p2p.port }}
        {{- if ne (int .Values.config.p2p.discoveryPort) (int .Values.config.p2p.port) }}
        - --discovery.port={{ .Values.config.p2p.discoveryPort }}
        {{- end }}
        {{- with .Values.config.p2p.nat }}
        - --nat={{ . }}
        {{- end }}
        {{- if .Values.config.p2p.noDiscovery }}
        - --disable-discovery
        {{- end }}
        {{- with .Values.config.p2p.discv5 }}
        {{- if .enabled }}
        - --enable-discv5-discovery
        - --discovery.v5.port={{ .port }}
        {{- with .addr }}
        - --discovery.v5.addr={{ . }}
        {{- end }}
        {{- if .lookupInterval }}
        - --discovery.v5.lookup-interval={{ .lookupInterval }}
        {{- end }}
        {{- if .disableV4 }}
        - --disable-discv4-discovery
        {{- end }}
        {{- end }}
        {{- end }}
        {{- with .Values.config.p2p.bootnodes }}
        - --bootnodes={{ join "," . }}
        {{- end }}
        {{- with .Values.config.p2p.trustedPeers }}
        - --trusted-peers={{ join "," . }}
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        - --metrics=0.0.0.0:{{ .Values.config.metrics.port }}
        {{- end }}
        {{- with .Values.config.rpcCache }}
        {{- if .maxBlocks }}
        - --rpc-cache.max-blocks={{ .maxBlocks }}
        {{- end }}
        {{- if .maxReceipts }}
        - --rpc-cache.max-receipts={{ .maxReceipts }}
        {{- end }}
        {{- if .maxHeaders }}
        - --rpc-cache.max-headers={{ .maxHeaders }}
        {{- end }}
        {{- end }}
        {{- if .Values.config.log.fileDirectory }}
        - --log.file.directory={{ .Values.config.log.fileDirectory }}
        {{- else }}
        - --log.file.max-files={{ .Values.config.log.fileMaxFiles }}
        {{- end }}
        {{- with .Values.config.rollup }}
        {{- with .sequencerHttp }}
        - --rollup.sequencer={{ . }}
        {{- end }}
        {{- if .disableTxPoolGossip }}
        - --rollup.disable-tx-pool-gossip
        {{- end }}
        {{- with .historicalRpc }}
        - --rollup.historicalrpc={{ . }}
        {{- end }}
        {{- end }}
        {{- with .Values.extraArgs }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- end }}
        env:
        - name: HOME
          value: {{ .Values.config.datadir | quote }}
        {{- with .Values.extraEnv }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.config.http.port }}
        - name: authrpc
          containerPort: {{ .Values.config.authrpc.port }}
        {{- if .Values.config.ws.enabled }}
        - name: ws
          containerPort: {{ .Values.config.ws.port }}
        {{- end }}
        {{- if .Values.config.metrics.enabled }}
        - name: metrics
          containerPort: {{ .Values.config.metrics.port }}
        {{- end }}
        - name: p2p-tcp
          containerPort: {{ .Values.config.p2p.port }}
          {{- if .Values.config.p2p.useHostPort }}
          hostPort: {{ .Values.config.p2p.port }}
          {{- end }}
          protocol: TCP
        - name: p2p-udp
          containerPort: {{ .Values.config.p2p.discoveryPort }}
          {{- if .Values.config.p2p.useHostPort }}
          hostPort: {{ .Values.config.p2p.discoveryPort }}
          {{- end }}
          protocol: UDP
        {{- if .Values.config.p2p.discv5.enabled }}
        - name: discv5-udp
          containerPort: {{ .Values.config.p2p.discv5.port }}
          {{- if .Values.config.p2p.useHostPort }}
          hostPort: {{ .Values.config.p2p.discv5.port }}
          {{- end }}
          protocol: UDP
        {{- end }}
        volumeMounts:
        - name: config
          mountPath: /config
        - name: data
          mountPath: {{ .Values.persistence.mountPath | default .Values.config.datadir }}
        - name: secrets
          mountPath: /secrets
        - name: scripts
          mountPath: /scripts
        {{- with .Values.extraVolumeMounts }}
        {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          {{- include "reth.healthcheck" (list $ .Values.livenessProbe) | nindent 10 }}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          {{- include "reth.healthcheck" (list $ .Values.readinessProbe) | nindent 10 }}
        {{- end }}
        {{- if .Values.startupProbe.enabled }}
        startupProbe:
          {{- include "reth.healthcheck" (list $ .Values.startupProbe) | nindent 10 }}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- if .Values.resizePolicy }}
        resizePolicy: {{- toYaml .Values.resizePolicy | nindent 10 }}
        {{- end }}
      volumes:
      - name: config
        emptyDir: {}
      - name: config-ro
        configMap:
          name: {{ template "reth.fullname" . }}-config
      - name: secrets
        secret:
          secretName: {{ template "reth.fullname" . }}
      - name: scripts
        configMap:
          name: {{ template "reth.fullname" . }}-scripts
      {{- if eq .Values.persistence.type "hostPath" }}
      - name: data
        hostPath:
          path: {{ .Values.persistence.hostPath.path }}
          type: {{ .Values.persistence.hostPath.type }}
      {{- end }}
      {{- with .Values.extraVolumes }}
      {{- tpl (toYaml .) $ | nindent 6 }}
      {{- end }}
  {{- if eq .Values.persistence.type "pvc" }}
  volumeClaimTemplates:
  - metadata:
      name: data
      labels:
        {{- include "reth.selectorLabels" . | nindent 8 }}
      {{- with .Values.persistence.pvc.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      accessModes:
      - {{ .Values.persistence.pvc.accessMode }}
      {{- if .Values.persistence.pvc.storageClass }}
      {{- if eq .Values.persistence.pvc.storageClass "-" }}
      storageClassName: ""
      {{- else }}
      storageClassName: {{ .Values.persistence.pvc.storageClass | quote }}
      {{- end }}
      {{- end }}
      resources:
        requests:
          storage: {{ .Values.persistence.pvc.size | quote }}
  {{- end }}
