apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "smokeping-prober.fullname" . }}
  labels:
    {{- include "smokeping-prober.labels" . | nindent 4 }}
data:
  config.yml: |
    {{- toYaml .Values.config | nindent 4 }}
