apiVersion: v1
kind: Service
metadata:
  name: {{ include "smokeping-prober.fullname" . }}
  labels:
    {{- include "smokeping-prober.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "smokeping-prober.selectorLabels" . | nindent 4 }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
