apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ton.fullname" . }}-scripts
  labels:
    {{- include "ton.labels" . | nindent 4 }}
data:
  init.sh: |-
    {{- tpl ($.Files.Get "files/init.sh") . | indent  4 }}
  config.py: |-
    {{- tpl ($.Files.Get "files/config.py") . | indent  4 }}
  api_healthcheck.py: |-
    {{- tpl ($.Files.Get "files/api_healthcheck.py") . | indent  4 }}
  node_healthcheck.sh: |-
    {{- tpl ($.Files.Get "files/node_healthcheck.sh") . | indent  4 }}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ton.fullname" . }}-api-config
  labels:
    {{- include "ton.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.config.api.env }}
  {{- if eq $key "TON_API_TONLIB_LITESERVER_CONFIG"}}
  {{ $key }}: "{{ $.Values.config.fullnode.root}}/{{ $value }}"
  {{- else if eq $key "TON_API_TONLIB_KEYSTORE"}}
  {{ $key }}: "{{ $.Values.config.fullnode.root}}/{{ $value }}"
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
  TON_API_HTTP_PORT: "{{ .Values.config.api.port }}"