apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "geth.fullname" . }}-scripts
  labels:
    {{- include "geth.labels" . | nindent 4 }}
data:
  check-readiness.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_check-readiness.tpl") . | nindent 4 }}
