{{- if .Values.authrpc.jwtsecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "geth.fullname" }}-jwt
type: Opaque
stringData:
  jwt.hex: |
    {{ .Values.authrpc.jwtsecret }}
{{- end }}
