{{- if and .Values.services.p2p.enabled (not .Values.config.node.p2p.useHostPort) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "geth.fullname" . }}-p2p
  {{- if .Values.services.p2p.annotations }}
  annotations:
    {{- toYaml .Values.services.p2p.annotations | nindent 4 }}
  {{- end }}
  labels:
    service-type: p2p
    {{- include "geth.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.p2p.type }}
  {{- with .Values.services.p2p.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.services.p2p.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.services.p2p.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.services.p2p.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  publishNotReadyAddresses: true
  ports:
    - name: p2p-tcp
      port: {{ .Values.services.p2p.port }}
      targetPort: p2p-tcp
      protocol: TCP
      {{- with .Values.services.p2p.nodePort }}
      nodePort: {{ . }}
      {{- end }}
  selector:
    {{- include "geth.selectorLabels" . | nindent 4 }}
{{- end }}
