{{- if and .Values.config.metrics.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "geth.fullname" . }}
  labels:
    {{- include "geth.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      service-type: metrics
      {{- include "geth.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: metrics
      path: /debug/metrics/prometheus
      {{- with (omit .Values.serviceMonitor "enabled") }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace | quote }}
{{- end }}
