apiVersion: v1
kind: Secret
metadata:
  name: {{ template "base-consensus.fullname" . }}
  labels:
    {{- include "base-consensus.labels" . | nindent 4 }}
data:
  jwt.hex: {{ .Values.config.jwt | b64enc | quote }}