{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "bsc.labels" . | nindent 4 }}
spec:
{{- with .Values.podDisruptionBudget }}
{{- if hasKey . "minAvailable" }}
  minAvailable: {{ .minAvailable }}
{{- else if hasKey . "maxUnavailable" }}
  maxUnavailable: {{ .maxUnavailable }}
{{- end }}
{{- if .unhealthyPodEvictionPolicy }}
  unhealthyPodEvictionPolicy: {{ .unhealthyPodEvictionPolicy }}
{{- end }}
{{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bsc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      bsc/role: {{ .Values.bsc.role }}
{{- end }}
