{{- if .Values.metrics.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "bsc.fullname" . }}
  labels: {{ include "bsc.labels" . | nindent 4 }}
spec:
  endpoints:
  - interval: {{ .Values.metrics.interval }}
    scrapeTimeout: {{ .Values.metrics.scrapeTimeout }}
    honorLabels: true
    port: {{ .Values.service.metricsPortName }}
    path: /metrics
    scheme: http
  {{- if .Values.failback.metrics.enabled }}
  - interval: {{ .Values.failback.metrics.interval }}
    scrapeTimeout: {{ .Values.failback.metrics.scrapeTimeout }}
    honorLabels: true
    port: {{ .Values.failback.metrics.service.name }}
    path: /metrics
    scheme: http
  {{- end }}
  {{- if .Values.bsc.metrics.enabled }}
  - interval: {{ .Values.bsc.metrics.interval }}
    scrapeTimeout: {{ .Values.bsc.metrics.scrapeTimeout }}
    honorLabels: true
    port: {{ .Values.bsc.metrics.service.name }}
    path: /debug/metrics/prometheus
    scheme: http
  {{- end }}
  jobLabel: {{ include "bsc.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bsc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
