apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "bsc.fullname" . }}
  labels:
{{ include "bsc.labels" . | indent 4 }}
spec:
  serviceName: "{{ .Release.Name }}-service"
  replicas: {{ .Values.replicaCount }} # by default is 1
  updateStrategy:
    {{- toYaml .Values.updateStrategy | nindent 4 }}
  podManagementPolicy: {{ .Values.podManagementPolicy }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "bsc.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      bsc/chain: {{ .Values.bsc.chain }}
      bsc/role: {{ .Values.bsc.role }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "bsc.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        bsc/chain: {{ .Values.bsc.chain }}
        bsc/role: {{ .Values.bsc.role }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.terminationGracePeriodSeconds }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- if .Values.bscCmdOverride }}
        command: [ "{{ .Values.bscCmd }}" ]
        {{- end }}
        args:
          - --config=/config/config.toml
          - --datadir={{ .Values.bsc.base_path }}
          - --syncmode={{ .Values.bsc.syncmode }}
          - --gcmode={{ .Values.bsc.gcmode }}
          - --maxpeers={{ .Values.bsc.maxpeers }}
          - --cache={{ .Values.bsc.cache }}
          - --snapshot=false
          - --port={{ .Values.service.p2pPort0 }}
          - --rpc.allow-unprotected-txs
          - --txlookuplimit=0
          - --cache.preimages
          - --diffsync
          {{- if and .Values.externalLBp2p .Values.externalLBp2pIP }}
          - --nat=extip:{{- .Values.externalLBp2pIP -}}
          {{- end }}
          {{- if .Values.bsc.noDiscovery }}
          - --nodiscover
          {{- end }}
          {{- if .Values.bsc.netrestrict }}
          - --netrestrict={{ .Values.bsc.netrestrict }}
          {{- end }}
          {{- if .Values.bsc.metrics.enabled }}
          - --metrics
          - --pprof
          - --pprof.addr=0.0.0.0
          - --pprof.port={{ .Values.bsc.metrics.service.port }}
          {{- end }}
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-env"
        workingDir: "{{ .Values.bsc.base_path }}"
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        ports:
          {{- range $val := .Values.service.ports }}
        - containerPort: {{ $val.port }}
          {{- if $val.hostPort }}
          hostPort: {{ $val.hostPort }}
          {{- end }}
          name: "{{ $val.name }}"
          protocol: {{ $val.protocol | default "TCP" }}
          {{- end }}
        volumeMounts:
        - name: bsc-config
          mountPath: /config
        - name: scripts
          mountPath: /scripts
        - name: probe-env
          mountPath: /env
        - name: bsc-pvc
          mountPath: {{ .Values.bsc.base_path }}
        {{- if .Values.livenessProbe }}
        startupProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - source /env/env.txt && /bin/sh /scripts/check_node_health.sh http://127.0.0.1:{{ .Values.service.rpcPort }} $StartupProbeTimestampDistinct last_synced_block.txt
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - source /env/env.txt && /bin/sh /scripts/check_node_health.sh http://127.0.0.1:{{ .Values.service.rpcPort }} $LivenessProbeTimestampDistinct last_synced_block.txt
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.livenessProbe.successThreshold }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}

        {{- end }}
        {{- if .Values.readinessProbe }}
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - source /env/env.txt && /bin/sh /scripts/check_node_readiness.sh --timestamp-distinct $ReadinessProbeTimestampDistinct
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          successThreshold: {{ .Values.readinessProbe.successThreshold }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        {{- end }}
      - name: logger
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: [ "tail","-F","{{ .Values.bsc.base_path }}/bsc.log" ]
        workingDir: "{{ .Values.bsc.base_path }}"
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
            readOnly: true
      {{- if .Values.metrics.enabled }}
      - name: metrics
        image: "{{ .Values.metrics.image.repository }}:{{ .Values.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy }}
        args:
          - -url
          - http://127.0.0.1:{{ .Values.service.rpcPort }}
      {{- end }}
      {{- if .Values.failback.enabled }}
      - name: nginx
        image: "{{ .Values.failback.image.repository }}:{{ .Values.failback.image.tag }}"
        imagePullPolicy: {{ .Values.failback.image.pullPolicy }}
        ports:
          - containerPort: {{ .Values.failback.port }}
            name: nginx
            protocol: TCP
        volumeMounts:
          - mountPath: /etc/nginx/
            name: nginx-config-volume
      {{- end }}
      {{- if .Values.failback.metrics.enabled }}
      - name: nginx-metrics
        image: "{{ .Values.failback.metrics.image.repository }}:{{ .Values.failback.metrics.image.tag }}"
        imagePullPolicy: {{ .Values.failback.metrics.image.pullPolicy }}
        args:
          - -nginx.scrape-uri=http://localhost:{{ .Values.failback.port }}/metrics
        ports:
          - containerPort: {{ .Values.failback.metrics.service.port }}
            name: {{ .Values.failback.metrics.service.name }}
            protocol: TCP
      {{- end }}
      {{- if .Values.rsyncd.enabled }}
      - name: rsyncd
        image: {{ .Values.rsyncd.image }}
        imagePullPolicy: IfNotPresent
        command:
          - /usr/bin/rsync
          - --daemon
          - --config=/config/rsyncd.conf
          - --no-detach
          - --port={{ .Values.rsyncd.service.port }}
        ports:
          - containerPort: {{ .Values.rsyncd.service.port }}
            name: {{ .Values.rsyncd.service.name }}
            protocol: TCP
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.rsyncd.bsc_path }}
            readOnly: true
          - name: rsyncd-config
            mountPath: /config
      {{- end }}
      initContainers:
      {{- if .Values.bsc.initGenesis }}
      - name: init-genesis
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: ["/bin/sh", "-c", "wget -O /tmp/mainnet.zip
        https://github.com/binance-chain/bsc/releases/download/{{ $.Chart.AppVersion }}/mainnet.zip &&
        cd /tmp && unzip mainnet.zip &&
        geth --datadir={{ .Values.bsc.base_path }} init /tmp/genesis.json"]
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- end }}
      {{- if .Values.bsc.initFromSnapshot }}
      - name: init-from-snapshot
        image: {{ .Values.bsc.initFromSnapshotImage }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - /scripts/init_from_snaphot.sh
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
          - name: scripts
            mountPath: /scripts
      {{- end }}
      {{- if .Values.bsc.initFromRsync }}
      - name: init-from-rsync
        image: {{ .Values.bsc.initFromRsyncImage }}
        imagePullPolicy: IfNotPresent
        command:
          - /bin/sh
          - /scripts/init_from_rsync.sh
        envFrom:
          - configMapRef:
              name: "{{ .Release.Name }}-env"
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
          - name: scripts
            mountPath: /scripts
      {{- end }}
      - name: remove-lock
        command:
          - rm
          - -f
          - {{ .Values.bsc.base_path }}/geth/LOCK
        image: busybox
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- if .Values.bsc.getNodeKey }}
      - name: get-nodekey
        command:
          - python
          - /scripts/get_nodekey.py
        image: python:slim
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
          - name: scripts
            mountPath: /scripts
      {{- end }}
      {{- if .Values.bsc.staticNodeKey }}
      - name: set-nodekey
        command:
          - sh
          - -c
          - "echo -n {{ .Values.bsc.staticNodeKey }} > {{ .Values.bsc.base_path }}/geth/nodekey"
        image: busybox:latest
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - name: bsc-pvc
            mountPath: {{ .Values.bsc.base_path }}
      {{- end }}
      volumes:
        - name: bsc-config
          configMap:
            name: "{{ .Release.Name }}-config"
        {{- if .Values.rsyncd.enabled }}
        - name: rsyncd-config
          configMap:
            name: "{{ .Release.Name }}-rsyncd-config"
        {{- end }}
        - name: scripts
          configMap:
            name: "{{ .Release.Name }}-scripts"
        - name: probe-env
          configMap:
            name: "{{ .Release.Name }}-probe-env"
        {{- if not .Values.persistence.enabled }}
        - name: bsc-pvc
          emptyDir: {}
        {{- end }}
        {{- if .Values.failback.enabled }}
        - name: nginx-config-volume
          configMap:
            name: "{{ .Release.Name }}-nginx-config"
        {{- end }}
  {{- if .Values.persistence.enabled }}
  volumeClaimTemplates:
    - metadata:
        creationTimestamp: null
        name: bsc-pvc
        labels:
          app: bsc
      spec:
        accessModes:
        - {{.Values.persistence.accessMode }}
        {{- if .Values.persistence.storageClass }}
        {{- if (eq "-" .Values.persistence.storageClass) }}
        storageClassName: ""
        {{- else }}
        storageClassName: "{{ .Values.persistence.storageClass }}"
        {{- end }}
        {{- end }}
        resources:
          requests:
            storage: {{ .Values.persistence.size }}
        volumeMode: Filesystem
  {{- end }}
