apiVersion: v2
name: ai-scale-auth
description: A Helm chart for Kubernetes
type: application
version: 0.1.0
appVersion: "0.1.0"
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.10.x
  - name: base
    version: 0.2.x
    repository: https://dysnix.github.io/charts
    tags:
      - dysnix-base
  - name: postgresql
    version: 10.x
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
    tags:
      - bitnami-postgresql
sources:
  - https://github.com/dysnix/charts
maintainers:
  - email: services@dysnix.com
    name: Dysnix
