{{- if .Values.crd.enabled }}
{{- range $key, $cr := .Values.crd.crs }}
---
apiVersion: autoscaling.ai.op.dysnix.org/v2
kind: AIPodAutoscaler
metadata:
  name: {{ $cr.name }}
{{/*  annotations:*/}}
{{/*    "helm.sh/hook": pre-install,pre-upgrade*/}}
{{/*    "helm.sh/hook-weight": "-1"*/}}
{{/*    "helm.sh/hook-delete-policy": before-hook-creation*/}}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ $cr.scaleTargetRef.kind }}
    name: {{ $cr.scaleTargetRef.name }}
  minReplicas: {{ $cr.minReplicas }}
  maxReplicas: {{ $cr.maxReplicas }}
  updateInterval: {{ $cr.updateInterval }}
  stepDuration: {{ $cr.stepDuration }}
  timeWindow: {{ $cr.timeWindow }}
  sources: {{ $cr.sources | toYaml | nindent 4 }}
{{- end }}
{{- end }}