{{- if and .Values.rbac.enabled .Values.serviceAccount.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - apps
    resources:
      - deployments
      - statefulsets
      - daemonsets
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups: [""]
    resources:
      - aipodautoscalers
      - aipodautoscaler
    verbs:
      - "*"
  - apiGroups: [""]
    resources:
      - aipodautoscalers/status
      - aipodautoscaler/status
    verbs:
      - "*"
  - apiGroups: ["autoscaling.ai.op.dysnix.org"]
    resources: ["*"]
    verbs: ["*"]
  - apiGroups:
      - autoscaling.ai.op.dysnix.org
    resources:
      - aipodautoscalers/status
      - aipodautoscaler/status
    verbs:
      - '*'
  - apiGroups:
      - autoscaling.ai.op.dysnix.org
    resources:
      - aipodautoscalers
      - aipodautoscaler
    verbs:
      - '*'
  - apiGroups:
      - authorization.k8s.io
    resources:
      - subjectaccessreviews
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - daemonsets/status
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - deployments/status
    verbs:
      - '*'
  - apiGroups:
      - apps
    resources:
      - statefulsets/status
    verbs:
      - '*'
  - apiGroups:
      - autoscaling.ai.op.dysnix.org
    resources:
      - aipodautoscalers/finalizers
      - aipodautoscaler/finalizers
    verbs:
      - '*'
  - apiGroups:
      - autoscaling.ai.op.dysnix.org
    resources:
      - aipodautoscalers/status
      - aipodautoscaler/status
    verbs:
      - '*'
  {{- if .Values.webhook.enabled }}
  - apiGroups:
      - admissionregistration.k8s.io
    resources:
      - mutatingwebhookconfigurations
      - validatingwebhookconfigurations
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  {{- end }}
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - update
      - delete
      - deletecollection
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "common.names.fullname" . }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "common.names.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "common.names.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}