{{- if .Values.webhook.enabled }}
{{- $certs := (include "get.certs" .) | fromJson }}
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: operator-certificates
  name: {{ .Values.webhook.certs.secretName }}
  namespace: {{ .Release.Namespace }}
data:
  tls.crt: {{ get $certs "tlsCrt" }}
  tls.key: {{ get $certs "tlsKey" }}
  ca.crt:  {{ get $certs "caCrt" }}
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "common.names.name" . }}-validating-webhook
webhooks:
  - admissionReviewVersions:
      - v1
      - v1beta1
    clientConfig:
      caBundle: {{ get $certs "caCrt" }}
      service:
        name: "{{ include "common.names.fullname" . }}"
        namespace: {{ .Release.Namespace }}
        path: /validate
    failurePolicy: Fail
    name: vaipodautoscaler.kb.io
    rules:
      - apiGroups:
          - autoscaling.ai.op.dysnix.org
        apiVersions:
          - v2
        operations:
          - CREATE
          - UPDATE
        resources:
          - aipodautoscalers
    sideEffects: None
{{- end }}