apiVersion: v1
appVersion: "1.29"
description: A Helm chart for Kubernetes
name: pritunl
version: 0.1.5
home: https://pritunl.com/
sources:
  - https://github.com/dysnix/charts
  - https://github.com/pritunl/pritunl
maintainers:
  - name: dennybaa
    email: dennybaa@gmail.com
