apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nifi-registry.fullname" . }}
  labels:
    {{- include "nifi-registry.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "nifi-registry.selectorLabels" . | nindent 6 }}
  serviceName: {{ include "nifi-registry.fullname" . }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "nifi-registry.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nifi-registry.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        {{- if .Values.flowProvider.git.enabled }}
        - name: git-clone
          image: "{{ .Values.initContainers.git.image }}:{{ .Values.initContainers.git.tag }}"
          command:
            - sh
            - -cex
            - |
              git clone $(NIFI_REGISTRY_GIT_URL) "/tmp/flow_storage" || git -C "/tmp/flow_storage" pull
              cp --dereference /ssh/id_rsa /ssh-dest/

              chown -R 1000:1000 /tmp/flow_storage /ssh-dest
          env:
            - name: NIFI_REGISTRY_GIT_URL
              value: {{ .Values.flowProvider.git.url }}          
            - name: NIFI_REGISTRY_GIT_USER
              value: {{ .Values.flowProvider.git.user }}          
            - name: NIFI_REGISTRY_GIT_PASSWORD
              value: {{ .Values.flowProvider.git.password }}
          {{- if .Values.initContainers.extraEnvs }}
            {{ toYaml .Values.initContainers.extraEnvs | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: "flow-storage"
              mountPath: /tmp
            {{- if .Values.ssh.known_hosts }}
            - name: sshcfgmap
              mountPath: /root/.ssh
              readOnly: true
            {{- end }}
            - name: git-key
              mountPath: /ssh
              readOnly: true
            - name: git-key-fixed
              mountPath: /ssh-dest
        {{- end }}
        {{- if .Values.persistence.enabled }}
        - name: take-data-dir-ownership
          image: "{{ .Values.initContainers.alpine.image }}:{{ .Values.initContainers.alpine.tag }}"
          command:
          command:
            - chown
            - -R
            - 1000:1000
            - /opt/nifi-registry/nifi-registry-current/database
            - /opt/nifi-registry/nifi-registry-current/flow_storage
          volumeMounts:
            - name: "database"
              mountPath: /opt/nifi-registry/nifi-registry-current/database
            - name: "flow-storage"
              mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
              subPath: flow_storage
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - bash
            - -ce
            - |
            {{- if .Values.flowProvider.postgres.enabled }}
              cd /opt/nifi-registry/nifi-registry-current/ext
              mkdir postgresql
              cd postgresql
              curl -k "{{ .Values.flowProvider.postgres.driverURL }}{{ .Values.flowProvider.postgres.fileName }}" -o "{{ .Values.flowProvider.postgres.fileName }}"
            {{- end }}
            {{- if .Values.ssh.known_hosts }}
              cp --verbose --dereference /sshcfgmap/known_hosts /home/nifi/.ssh/
              {{- if .Values.ssh.config }}
                cp --verbose --dereference /sshcfgmap/config /home/nifi/.ssh/
              {{- end }}
              {{- if .Values.flowProvider.git.enabled }}
                cp --verbose --dereference /ssh/id_rsa /home/nifi/.ssh/
              {{- end }}
            {{- end }}
              ${NIFI_REGISTRY_BASE_DIR}/scripts/start.sh
          ports:
            - name: http
              containerPort: 18080
              protocol: TCP
          env:
          {{- if .Values.flowProvider.git.enabled }}
            - name: NIFI_REGISTRY_FLOW_PROVIDER
              value: git
            - name: NIFI_REGISTRY_GIT_REMOTE
              value: {{ .Values.flowProvider.git.remote }}
            - name: NIFI_REGISTRY_GIT_USER
              value: {{ .Values.flowProvider.git.user }}          
            - name: NIFI_REGISTRY_GIT_PASSWORD
              value: {{ .Values.flowProvider.git.password }} 
          {{- end }}
          {{- if .Values.flowProvider.postgres.enabled }}
            - name: NIFI_REGISTRY_FLOW_PROVIDER
              value: postgres
            - name: NIFI_REGISTRY_DB_DIR
              value: ./ext/postgresql
            - name: NIFI_REGISTRY_DB_CLASS
              value: {{ .Values.flowProvider.postgres.driverClass }}
            - name: NIFI_REGISTRY_DB_URL
              value: {{ .Values.flowProvider.postgres.url }}
            - name: NIFI_REGISTRY_DB_USER
              value: {{ .Values.flowProvider.postgres.username }}
            - name: NIFI_REGISTRY_DB_PASS
              value: {{ .Values.flowProvider.postgres.password }}
          {{- end }}
          {{- if .Values.extraEnvs }}
            {{ toYaml .Values.extraEnvs | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{ if .Values.persistence.enabled }}
            - name: "database"
              mountPath: /opt/nifi-registry/nifi-registry-current/database
            {{ end }}
            {{ if or .Values.persistence.enabled .Values.flowProvider.git.enabled }}
            - name: "flow-storage"
              mountPath: /opt/nifi-registry/nifi-registry-current/flow_storage
              subPath: flow_storage
            {{ end }}
            {{- if .Values.ssh.known_hosts }}
            - name: sshcfgmap
              mountPath: /sshcfgmap
              readOnly: true
            - name: sshdir
              mountPath: /home/nifi/.ssh
              readOnly: false
            {{- end }}
            {{- if .Values.flowProvider.git.enabled }}
            {{- if .Values.flowProvider.git.config.enabled }}
            - name: git-config
              mountPath: /home/nifi/.gitconfig
              subPath: gitconfig
              readOnly: true
            {{- end }}
            - name: git-key-fixed
              mountPath: /ssh
              readOnly: true
            {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          readinessProbe:
            tcpSocket:
              port: 18080
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 1
            successThreshold: 2
            failureThreshold: 3
      volumes:
        {{- if .Values.ssh.known_hosts }}
        - name: sshdir
          emptyDir: {}
        - name: sshcfgmap
          configMap:
            name: {{ template "nifi-registry.fullname" . }}-ssh-config
            defaultMode: 0644
        {{- end }}
        {{- if .Values.flowProvider.git.enabled }}
        {{- if not .Values.persistence.enabled }}
        - name: flow-storage
          emptyDir: {}
        {{- end }}
        {{- if .Values.flowProvider.git.config.enabled }}
        - name: git-config
          secret:
            secretName: {{ include "flowProvider.git.config.secretName" . }}
            defaultMode: 0400
        {{- end }}
        - name: git-key
          secret:
            {{- if .Values.flowProvider.git.secretName }}
            secretName: {{ .Values.flowProvider.git.secretName }}
            {{- else }}
            secretName: {{ template "nifi-registry.fullname" . }}-git-deploy
            {{- end }}
            defaultMode: 0400
        - name: git-key-fixed
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  {{ if .Values.persistence.enabled }}
  volumeClaimTemplates:
  - metadata:
      name: database
    spec:
      accessModes:
      - ReadWriteOnce
      {{ if .Values.persistence.database.storageClass }}
      {{ if (eq "-" .Values.persistence.database.storageClass) }}
      storageClassName: ""
      {{ else }}
      storageClassName: "{{ .Values.persistence.database.storageClass }}"
      {{ end }}
      {{ end }}
      resources:
        requests:
          storage: {{ .Values.persistence.database.size | quote }}
  - metadata:
      name: flow-storage
    spec:
      accessModes:
      - ReadWriteOnce
      {{ if .Values.persistence.flowStorage.storageClass }}
      {{ if (eq "-" .Values.persistence.flowStorage.storageClass) }}
      storageClassName: ""
      {{ else }}
      storageClassName: "{{ .Values.persistence.flowStorage.storageClass }}"
      {{ end }}
      {{ end }}
      resources:
        requests:
          storage: {{ .Values.persistence.flowStorage.size | quote }}
  {{ end }}
