apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "bor.fullname" . }}-config
  labels:
    {{- include "bor.labels" . | nindent 4 }}
data:
  config.toml: |-
    {{- include "toml.config" (list $ .Values.config) | indent 4 }}
