{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "bor.serviceAccountName" . }}
  labels:
    {{- include "bor.labels" . | nindent 4 }}
{{- end }}
