{{- with .Values.services.heimdall }}
{{- if .enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bor.fullname" $ }}-heimdall
  {{- with .annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    service-type: heimdall
    {{- include "bor.labels" $ | nindent 4 }}
spec:
  type: {{ .type }}
  {{- with .loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .port }}
      targetPort: http
  selector:
    {{- include "bor.selectorLabels" $ | nindent 4 }}
{{- end }}
{{- end }}
