{{- if .Values.services.heimdall.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "bor.fullname" . }}-heimdall
  {{- if .Values.services.heimdall.annotations }}
  annotations:
    {{- .Values.services.heimdall.annotations | nindent 4 }}
  {{- end }}
  labels:
    service-type: heimdall
    {{- include "bor.labels" . | nindent 4 }}
spec:
  type: {{ .Values.services.heimdall.type }}
  {{- with .Values.services.heimdall.loadBalancerIP }}
  loadBalancerIP: {{ . }}
  {{- end }}
  {{- with .Values.services.heimdall.clusterIP }}
  clusterIP: {{ . }}
  {{- end }}
  {{- with .Values.services.heimdall.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.services.heimdall.internalTrafficPolicy }}
  internalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with .Values.services.rpc.publishNotReadyAddresses }}
  publishNotReadyAddresses: {{ . }}
  {{- end }}
  ports:
    - name: http
      port: {{ .Values.services.heimdall.port }}
      targetPort: http
  selector:
    {{- include "bor.selectorLabels" . | nindent 4 }}
{{- end }}
