apiVersion: v2
name: reth
description: Reth Ethereum execution client Helm Chart

version: 0.0.7
appVersion: v2.0.0

keywords:
  - reth
  - cryptocurrency
  - blockchain
  - ethereum

sources:
  - https://github.com/dysnix/charts

maintainers:
  - email: services@dysnix.com
    name: Dysnix
