apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "arbitrum.fullname" . }}
  labels:
    {{- include "arbitrum.labels" . | nindent 4 }}
data:
  config.json: |
    {{- .Values.config | toPrettyJson | replace "\\u0026" "&" | replace "\\u003c" "<" | replace "\\u003e" ">" | nindent 4 }}
