{{- if or .Values.initFromS3.enabled .Values.syncToS3.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "arbitrum.fullname" . }}-s3-secret
data:
  S3_ENDPOINT_URL: {{ .Values.s3config.endpointUrl | toString | b64enc }}
  AWS_ACCESS_KEY_ID: {{ .Values.s3config.accessKeyId | toString | b64enc }}
  AWS_SECRET_ACCESS_KEY: {{ .Values.s3config.secretAccessKey | toString | b64enc }}
{{- end }}
