---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "pritunl.fullname" . }}
  labels:
{{ include "pritunl.labels" . | indent 4 }}
data:
  pritunl.conf: |
    {{- .Values.conf | toPrettyJson | nindent 4 }}
