{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "pritunl.serviceAccountName" . }}
  labels:
{{ include "pritunl.labels" . | indent 4 }}
{{- end -}}
