apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tokenbridge.fullname" . }}-env
  labels:
  {{- include "tokenbridge.labels" . | nindent 4 }}
data:
  {{- range $name, $value := .Values.envs }}
  {{ $name }}: {{ $value|b64enc|quote }}
  {{- end }}
  {{- if not .Values.bridge.ORACLE_QUEUE_URL }}
  ORACLE_QUEUE_URL: redis://{{ include "tokenbridge.fullname" . }}-rabbitmq
  {{ end }}
  {{- if not .Values.bridge.ORACLE_REDIS_URL }}
  ORACLE_REDIS_URL: redis://{{ include "tokenbridge.fullname" . }}-redis-master
  {{ end }}
