apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "solana.fullname" . }}-scripts
  labels:
    {{- include "solana.labels" . | nindent 4 }}
data:
  start.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_start.tpl") . | nindent 4 }}
  health.sh: |-
    {{- include (print $.Template.BasePath "/scripts/_health.tpl") . | nindent 4 }}
