{{- if and .Values.metrics.enabled .Values.metrics.prometheusRule.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ template "agave.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.prometheusRule.namespace | quote }}
  labels: {{- include "agave.labels" . | nindent 4 }}
    {{- if .Values.metrics.prometheusRule.additionalLabels }}
    {{- toYaml .Values.metrics.prometheusRule.additionalLabels | nindent 4 }}
    {{- end }}
spec:
  groups:
    - name: {{ include "agave.fullname" . }}
      rules: {{- tpl (toYaml .Values.metrics.prometheusRule.rules) $ | nindent 8 }}
{{- end }}
