{{/* vim: set filetype=mustache: */}}
{{- if eq (.Values.monitoring.enabled | toString) "true" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "common.names.fullname" . }}-prometheus-service-monitor
  {{- $standardLabels := fromYaml (include "common.labels.standard" .) -}}
  {{- $labels := merge $standardLabels .Values.monitoring.labels }}
  labels: {{ toYaml $labels | nindent 4 }}
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: monitoring
  selector:
    matchLabels: {{ include "common.labels.matchLabels" . | nindent 6 }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}