apiVersion: v1
kind: Secret
metadata:
  name:  "{{ .Release.Name }}-config"
  labels:
{{ include "bitcoind.labels" . | indent 4 }}
type: Opaque
data:
  {{ .Values.bitcoind.configurationFileName }}: |-
  {{- include (print $.Template.BasePath "/_bitcoin.conf") . | b64enc | nindent 4 }}
