apiVersion: v2
appVersion: "1.29"
description: A Helm chart for Kubernetes
name: pritunl
version: 0.2.7
home: https://pritunl.com/
sources:
  - https://github.com/dysnix/charts
  - https://github.com/pritunl/pritunl

maintainers:
  - name: dennybaa
    email: dennybaa@gmail.com
  - name: vladstarr
    email: vladstarrr@icloud.com

dependencies:
  - name: common
    repository: oci://ghcr.io/dysnix/charts
    tags:
      - bitnami-common
    version: 1.10.4
  - name: mongodb
    version: 10.30.12
    repository: oci://ghcr.io/dysnix/charts
    condition: mongodb.enabled
