apiVersion: v2
appVersion: "1.29"
description: A Helm chart for Kubernetes
name: pritunl
version: 0.2.2
home: https://pritunl.com/
sources:
  - https://github.com/dysnix/charts
  - https://github.com/pritunl/pritunl

maintainers:
  - name: dennybaa
    email: dennybaa@gmail.com
  - name: vladstarr
    email: vladstarrr@icloud.com

dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.10.x
  - name: mongodb
    version: ~10.30.x
    repository: https://charts.bitnami.com/bitnami
    condition: mongodb.enabled
