{{/* vim: set filetype=helm: */}}
{{- define "app.resources.secret" -}}
{{- if .Values.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "common.names.fullname" . }}-{{ ._include.name }}
  namespace: {{ include "common.names.namespace" . | quote }}
  annotations:
    {{- with .Values.commonAnnotations }}
      {{- include "common.tplvalues.render" ( dict "value" . "context" $ ) | nindent 4 }}
    {{- end }}
    {{- with .Values.annotations }}
      {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  labels:
    {{- include "common.labels.standard" . | nindent 4 }}
    {{- include "app.labels.component" . | nindent 4 }}
    {{- if .Values.commonLabels }}
      {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
type: Opaque
{{- if ._include.value.data }}
data:
  {{- toYaml ._include.value.data | nindent 2 }}
{{- end }}
{{- if ._include.value.stringData }}
stringData:
  {{- $dict := dict -}}
  {{- range $key, $value := ._include.value.stringData -}}
    {{/* Render value first, since it's possible to pass a complex type (i.e map) */}}
    {{- $_ := set $dict $key (include "common.tplvalues.render" (dict "value" $value "context" $)) -}}
  {{- end -}}
  {{- $dict | toYaml | nindent 2 }}
{{- end }}
{{- end }}
{{- end -}}

{{- define "app.resources.secrets" -}}
  {{- range $name, $value := .Values.secrets | default dict }}
    {{- include "app.resources.include" (dict "resource" "secret" "name" $name "value" $value "top" $) }}
  {{- end }}
{{- end -}}

{{/* Include the resource */}}
{{- if eq "direct" (include "app.chart.mode" .) -}}
  {{- range $_, $component := concat (list "") $.Values.app.components -}}
    {{- $values := ternary $.Values (get $.Values "component") (eq $component "") | default dict -}}
    {{- include "app.secrets" (dict "component" $component "values" $values "top" $) -}}
  {{- end -}}
{{- end -}}